-- Auto-generated by Matugen

require('base16-colorscheme').setup {
  base00 = '#c1c1ff',
  base01 = '#0c0e13',
  base02 = '#191c20',
  base03 = '#43474e',
  base04 = '#c4c6cf',
  base05 = '#e1e2e9',
  base06 = '#2e3035',
  base07 = '#37393e',

  base08 = '#ffb4ab',
  base09 = '#dbbce1',
  base0A = '#bdc7dc',
  base0B = '#a8c8ff',
  base0C = '#563e5d',
  base0D = '#254777',
  base0E = '#3e4758',
  base0F = '#93000a',
}

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#254777',
  fg = '#c1c1ff',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#f8d8fe',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#dbbce1',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bdc7dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#3f5f90',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0c0e13',
  fg = '#a8c8ff',
})
